### ISSUE TITLE
Completar la sección de Productos con descripción

### ISSUE THREAD

**Issue by denissegg** [aorimx/ef-s#39]
La sección de productos debe tener la descripción debajo de cada fotografía. Al momento de dar clic en la imagen, despliega la descripción y la flecha de rota hacia abajo. 

![3 productos](https://user-images.githubusercontent.com/33732979/33334252-d9a0ca92-d42e-11e7-912b-7c3f6a5d0e5e.jpg)

# Elevadores Corporativos

Velocidad traslado es de 0.5 a 3 m/seg. 

Capacidad de carga desde 250 kg hasta 3000 kg.

Accesos o ingresos desde 60 cm hasta 2.50 m.

Posibilidad de ingresos a 2 frentes. 

Oportunidad de instalación con o sin cuarto de máquinas.

Reducción de dimensiones totales necesarias para instalación, empleando un sistema de tracción de 100 milímetros.

# Elevadores residenciales

Velocidad traslado es de 0.5 a 1 m/seg. 

Capacidad de carga desde 250 kg hasta 3000 kg.

Accesos o ingresos desde 60 cm hasta 2.50 m.

Posibilidad de ingresos a 2 frentes. 

Oportunidad de instalación con o sin cuarto de máquinas.

Reducción de dimensiones totales necesarias para instalación, empleando un sistema de tracción de 100 milímetros.

**Nuestros elevadores residenciales o ejecutivos pueden ser compatibles eléctricamente con alimentaciones BI- FASICAS.** 

# Proyectos Personalizados

Velocidad traslado es de 0.5 a 3 m/seg.

Capacidad de carga desde 250 kg hasta 3000 kg.

Accesos o ingresos desde 60 cm hasta 2.50 m.

Opción de hasta 3 ingresos (180 grados). 

Oportunidad de instalación con o sin cuarto de máquinas.

Probabilidad de sistema de tracción, cables o bandas según requerimientos.

Adaptación dentro de espacios geométricamente atípicos. 

Diseño del elevador con variaciones geométricas como lo son: estructuras triangulares. 

Posibilidad de rutas de traslado no lineales. 

Decoraciones y acabados personalizados.

Opciones de desarrollos para parques de diversiones,museos, centros turísticos y hoteles.

# Escaleras Eléctricas

Con sensores de presencia intuitiva o inteligente, perfectos para prevención de accidentes y consumo inteligente de energía.
 
Con sistemas de iluminación LED interior a través de todo el recorrido de la escalera o corredor.

Opción de desarrollos para exteriores con capacidad de funcionar ante cualquier tipo de intemperismo. 
 
Posibilidad de desarrollos de 4 m de altura hasta 24 m. Con grados de inclinación desde 0 grados hasta 35 grados. 

# Aceras Móviles

Con sensores de presencia intuitiva o inteligente, perfectos para prevención de accidentes y consumo inteligente de energía.
 
Con sistemas de iluminación LED interior a través de todo el recorrido de la escalera o corredor.

Opción de desarrollos para exteriores con capacidad de funcionar ante cualquier tipo de intemperismo. 
 
Posibilidad de desarrollos de 4 m de altura hasta 24 m. Con grados de inclinación desde 0 grados hasta 35 grados. 

# Elevadores Uso Doméstico

Velocidades de traslado de 0.3 a 0.5 m/seg. 
Capacidades de carga desde 50 kg hasta 300 kg.

Accesos o ingresos desde 40 cm hasta 1 m.
Oportunidad de ingresos a 2 frentes. 
Posibilidad de adaptación con o sin cuarto de máquinas. 

Opción de desarrollo e instalación sin preparaciones arquitectónicas previas. 
 
**Compatibilidad eléctrica MONO FASICA, BI-FASICA Y TRI–FASICA.**

# Montacargas

Velocidad traslado es de .5 a 1 m/seg. 

Capacidad de carga desde 2000 kg hasta 6000 kg.

Accesos o ingresos desde 1 m hasta 2.50 m.
Oportunidad de ingresos a 2 frentes. 

Posibilidad de instalación con o sin cuarto de máquinas.

# Apila Autos

Soporta hasta 7,000 lb.
 
Altura max. de levante 2.10 m.

Velocidad mínima de recorrido 26 segundos.
 
Voltaje requerido 220 Volts AC.

Operación electrohidráulica.

Seguros electromecánicos.

Descenso manual.

Pintura electrostática.

# Accesorios

Encuentra todos los accesorios en nuestra tienda en línea

**Comment by kikinbmk10** [comment]
me costo un buen hacer esto.
